# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Publish to npm
on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish (e.g., 1.0.0)"
        required: true
      release_notes:
        description: "Release notes"
        required: false
        default: "See CHANGELOG.md for details"
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for creating releases
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run linting
        run: npm run lint || echo "Linting issues found but continuing"
      - name: Update version (manual trigger)
        if: github.event_name == 'workflow_dispatch'
        run: |
          VERSION=${{ github.event.inputs.version }}
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
          npm version $VERSION --no-git-tag-version
      - name: Extract version from release (release trigger)
        if: github.event_name == 'release'
        run: |
          RELEASE_VERSION=${{ github.event.release.tag_name }}
          # Remove 'v' prefix if present
          VERSION=${RELEASE_VERSION#v}
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
          npm version $VERSION --no-git-tag-version
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create GitHub Release (manual trigger)
        if: github.event_name == 'workflow_dispatch'
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.RELEASE_VERSION }}
          name: Release v${{ env.RELEASE_VERSION }}
          body: ${{ github.event.inputs.release_notes }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create summary
        run: |
          echo "## Package Published! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Package: **n8n-nodes-quipu**" >> $GITHUB_STEP_SUMMARY
          echo "Version: **v${{ env.RELEASE_VERSION }}**" >> $GITHUB_STEP_SUMMARY
          echo "Registry: [npmjs.com](https://www.npmjs.com/package/n8n-nodes-quipu)" >> $GITHUB_STEP_SUMMARY

          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "GitHub Release: [v${{ env.RELEASE_VERSION }}](https://github.com/${{ github.repository }}/releases/tag/v${{ env.RELEASE_VERSION }})" >> $GITHUB_STEP_SUMMARY
          fi
